spring.application.name=saucedemo
server.port=8080

# Conexion a Neon (PostgreSQL)
# La password se toma del archivo .env (variable DB_PASSWORD), que NO se sube al repositorio.

spring.datasource.url=jdbc:postgresql://localhost:5432/saucedemo
spring.datasource.username=saucedemo
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
